<?php
/**
 * alerts.php
 * Reusable include for displaying session-based feedback messages
 */

$msg_types = [
    'add_success' => 'success',
    'edit_success' => 'success',
    'delete_success' => 'success',
    'import_success' => 'success',
    'success_message' => 'success',
    
    'add_error' => 'error',
    'edit_error' => 'error',
    'delete_error' => 'error',
    'import_error' => 'error',
    'error_message' => 'error'
];

foreach ($msg_types as $key => $type):
    if (isset($_SESSION[$key])):
        $class = ($type === 'success') ? 'alert-success' : 'alert-error';
        $icon = ($type === 'success') ? 'check-circle' : 'exclamation-circle';
?>
    <div class="alert <?= $class ?>">
        <i class="fas fa-<?= $icon ?>"></i>
        <div>
            <?= $_SESSION[$key]; ?>
            <?php if ($key === 'add_success' && isset($_SESSION['generated_password'])): ?>
                <div style="background: white; padding: 0.75rem; border-radius: 4px; border: 1px solid #bbf7d0; margin-top: 0.5rem;">
                    <span style="font-size: 0.8rem; color: #666; display: block; margin-bottom: 0.25rem;">Autogenerated Password:</span>
                    <code><?= htmlspecialchars($_SESSION['generated_password']) ?></code>
                </div>
                <?php unset($_SESSION['generated_password']); ?>
            <?php endif; ?>
        </div>
    </div>
<?php 
        unset($_SESSION[$key]);
    endif;
endforeach; ?>
